### ISSUE TITLE
[BUG] Dependency upgrades

### ISSUE THREAD

**Issue by TheAyes** [ChromexUnderscore/OriginsTweaks#28]
Pretty easy to solve.
Dependency exactly requires Pehkui v3.4.0 but doesn't try to load newer versions.
Also might be incompatible with quilt but it could've been the same error as above. Can check that after an update.

**Comment by TheAyes** [comment]
Oh also it only wants minecraft 1.19.0 and none above.

**Comment by ChromexUnderscore** [comment]
> Oh also it only wants minecraft 1.19.0 and none above.

That is on purpose, because the origins mod breaks on versions above 1.19.0, which I had to find out painfully over days of troubleshooting and testing.
Also, Pehkui seems to break rendering in some scenarios, eg view bobbing isn't working when activated, 3rd person views are pitch black and white and post processing shaders are either black or not applying...
I'll test older versions, but I'm pretty sure that 1.19 changed something that breaks pehkui

**Comment by TheAyes** [comment]
As far as I can tell Pehkui is working fine here :o
I'm using 3.4.1 with the Extra Origins "Inchling" origin. No issues to be seen here ^-^

**Comment by ChromexUnderscore** [comment]
I'll test 3.4.1

**Comment by ChromexUnderscore** [comment]
> As far as I can tell Pehkui is working fine here :o I'm using 3.4.1 with the Extra Origins "Inchling" origin. No issues to be seen here ^-^ ![image](https://user-images.githubusercontent.com/68541335/185927152-1dfb8774-d63d-4340-8a6e-e1f906cac4d2.png)
> 
> Bobbing works too.

Okay, Pehkui 3.4.1 seems to work, I'll update the dependencies!

**Comment by ChromexUnderscore** [comment]
> > As far as I can tell Pehkui is working fine here :o I'm using 3.4.1 with the Extra Origins "Inchling" origin. No issues to be seen here ^-^ ![image](https://user-images.githubusercontent.com/68541335/185927152-1dfb8774-d63d-4340-8a6e-e1f906cac4d2.png)
> > Bobbing works too.
> 
> Okay, Pehkui 3.4.1 seems to work, I'll update the dependencies!

Updated!
