### ISSUE TITLE
Aurophobia doesn't work fully.

### ISSUE THREAD

**Issue by Chargoal** [ChromexUnderscore/OriginsTweaks#31]
Tried to stand near Golden block, Block of raw gold and Gold ore. No debuffs apply to me.
Weakness to gold (more damage from gold tools) seems to work and I can't wear golden armor, so it seems only the fear of Blocks part doesn't work.

**Comment by Chargoal** [comment]
I am not too experienced in this, so I might be wrong. 
Possible solution: change block condition "origins:block_in_radius" to "origins:adjacent" as it seems there's no "block_in_radius" condition in Origins' author's documentation on creating datapacks.
![image](https://user-images.githubusercontent.com/62655322/190198139-7d998b99-0cec-4574-a9af-497db1dd2894.png)

**Comment by ChromexUnderscore** [comment]
> Tried to stand near Golden block, Block of raw gold and Gold ore. No debuffs apply to me.
> Weakness to gold (more damage from gold tools) seems to work and I can't wear golden armor, so it seems only the fear of Blocks part doesn't work.

Yeah, I see the Issue. I added golden blocks from the charm mod, this causes Minecraft to not load the Block tag for gold blocks due to unknown items if you don't have charm installed.
I can fix that easily by rewriting the block condition to look for either ``originstweaks:golden_blocks`` or ``originstweaks:golden_blocks_charm`` rather than including the charm one in the base tag.
Thanks for helping so much tho!

**Comment by Chargoal** [comment]
I have charm installed to be clear, so it isn't a problem. Maybe you're right and it's the tag that doesn't work for some reason.
(Thanks for actively working on such an amazing addon :3)

**Comment by Chargoal** [comment]
Okay, so I tried removing "#originstweaks:golden_blocks_charm" from golden_blocks.json and nothing changed... So there it is. I wish I helped - I have no other ideas how to fix this except maybe changing entity condition to something else which I don't know.
Hope you'll find it quick enough.
