### ISSUE TITLE
Enderian Reflex: When Underground, Reflex teleports you to highest point

### ISSUE THREAD

**Issue by lavabrothers** [ChromexUnderscore/OriginsTweaks#35]
**Describe the bug**
The bug, unless this is an intended feature, causes the Enderian Reflex passive to cause the player to be teleported to the surface, or the highest point right above the player. This behavior is similar to the Nether Roof bug, however I can confirm that the Nether Roof bug is not in this version. Seems to only in the Overworld. I tested this in a Small caves, Ancient Cities, Nether, and End. I varied the distance from the surface in the Overworld, though testing suggests that this is not a factor.

**To Reproduce**
1. Choose Enderian as your origin
2. Go to a cave or underground environment in the Overworld. Size of the environment doesn't seem to matter
3. Either find or spawn a mob that shoots projectiles (I used Skeletons)
4. Make sure you are in survival/adventure and have enough health to withstand the projectile
5. Profit

**Expected behavior**
The player should either teleport a short distance away or phase through projectile. They should not teleport to highest point unless it is close

**Versions**
Please also submit your Software Versions, such as:

+ SteamOS/Linux Mint
+ Java 17
+ Minecraft 1.20.1 
+ Fabric Loader 0.14.21
+ Origins Mod 1.10.1
+ Pehkui 3.7.6
+ Fabric API 0.84.0
+ OriginsTweaks 1.14.4

-No Crashlog needed

-All mods required are installed

Note: This seems to be a regression in 1.14.4 of the Origins Tweaks Mod, as this behavior was originally fixed in the Nether Roof hotfix in version 1.14.2. Reverting to this version seems to fix the bug. My guess is that the changes in 1.14.4 to fix the reflex's Nether exclusivity made the bug reemerge

**Comment by lavabrothers** [comment]
To clarify 1.14.2 won't run on 1.20.1, but based on 1.19.4 behavior it would fix the bug here

**Comment by ChromexUnderscore** [comment]
Thank you for reporting this bug!
Unfortunately, this is a side effect of the /spreadplayers command, but there is an optional value to specify the max y which the command can target.
I can probably use an if-else list to try and limit the max y relative to the player's current y.

**Comment by ChromexUnderscore** [comment]
> To clarify 1.14.2 won't run on 1.20.1, but based on 1.19.4 behavior it would fix the bug here

Thank you for reporting this bug!
Unfortunately, this is a side effect of the /spreadplayers command, but there is an optional value to specify the max y which the command can target, which I used in order to fix the nether roof bug.
I can probably use an if-else list to try and limit the max y relative to the player's current y.

**Comment by ChromexUnderscore** [comment]
Thank you for reporting this bug!
Unfortunately, this is a side effect of the /spreadplayers command, but there is an optional value to specify the max y which the command can target, which I used in order to fix the nether roof bug.
I can probably use an if-else list to try and limit the max y relative to the player's current y.

**Comment by ChromexUnderscore** [comment]
Fixed in OriginsTweaks Version 1.15.0
