### ISSUE TITLE
quilt.mod.json crash

### ISSUE THREAD

**Issue by V-lpen** [ChromexUnderscore/OriginsTweaks#41]
https://mcpaste.io/549cfa152d718fda

Crashes on quilt latest (1.20.1,  0.20.0-beta.11)
1.15.3 originstweaks

**Comment by ChromexUnderscore** [comment]
At the first glance on the report you've submitted, it says that you're using an outdated version of quilt,which doesn't support a feature used in the quilt metadata file.
But knowing me I probably messed it up...
I've added a quilt metadata file because someone requested it, but if it causes crashes, I will remove it.
Fabric mods are mostly going to work with the quilt loader as far as I know.

**Comment by jwaxy** [comment]
same error

**Comment by jwaxy** [comment]
fixed it by removing quilt.mod.json
